---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:

  - ec2:
      region: "{{ aws_region }}"
      image: ami-000
      exact_count: 0
      count_tag: { Name: "{{ aws_instance_name }}" }
      wait: yes

  # NOTE: Very occasionally you may experience a race condition whereby deleting
  # the security group will fail because it is still associated with the network
  # interface of the recently terminated EC2 instance.  Deletion times of
  # network interfaces seems to very. Eventually however, Amazon will cleanup
  # the interfaces and you'll be safe to re-run this playbook.
  - ec2_group:
      region: "{{ aws_region }}"
      name: "{{ aws_security_group_name }}"
      description: 'All egress, whitelisted SSH ingress.'
      state: absent

  - ec2_key:
      region: "{{ aws_region }}"
      name: "{{ aws_key_pair_name }}"
      state: absent
      wait: yes

  - file: >
      path="./{{ aws_key_pair_name }}.pem"
      state=absent
